<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Warehouse\WarehouseBooking;
use Carbon\Carbon;

class WarehouseBookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bookings = [
            [
                'user_id' => 22,
                'warehouse_unit_id' => 1,
                'booking_reference' => 'WH-' . strtoupper(substr(uniqid(), -8)),
                'status' => 'pending',
                'company_name' => 'Acme Corporation',
                'contact_person' => 'John Doe',
                'phone' => '+1-555-1001',
                'email' => 'john.doe@acme.com',
                'company_address' => '123 Business Street, New York, NY 10001',
                'storage_type' => 'dry',
                'required_space' => 1000.00,
                'goods_type' => 'Electronics',
                'goods_description' => 'Consumer electronics and accessories',
                'estimated_weight' => 5000.00,
                'special_requirements' => json_encode(['climate_control' => true, 'security_cameras' => true]),
                'amenities' => json_encode(['forklift', 'loading_dock']),
                'start_date' => Carbon::now()->addDays(7),
                'end_date' => Carbon::now()->addMonths(6),
                'duration_months' => 6,
                'access_hours' => '24/7',
                'special_instructions' => 'Handle with care - fragile items',
                'monthly_rate' => 5000.00,
                'security_deposit' => 10000.00,
                'setup_fee' => 500.00,
                'total_amount' => 30000.00,
                'tax_amount' => 3000.00,
                'final_amount' => 33500.00,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'pending',
                'terms_accepted' => true,
                'insurance_required' => true,
                'notes' => 'Initial booking for electronics storage',
            ],
            [
                'user_id' => 22,
                'warehouse_unit_id' => 1,
                'booking_reference' => 'WH-' . strtoupper(substr(uniqid(), -8)),
                'status' => 'confirmed',
                'company_name' => 'TechSupply Inc',
                'contact_person' => 'Jane Smith',
                'phone' => '+1-555-1002',
                'email' => 'jane.smith@techsupply.com',
                'company_address' => '456 Tech Avenue, San Francisco, CA 94102',
                'storage_type' => 'dry',
                'required_space' => 1500.00,
                'goods_type' => 'Computer Hardware',
                'goods_description' => 'Servers and networking equipment',
                'estimated_weight' => 8000.00,
                'special_requirements' => json_encode(['temperature_control' => true, 'dust_free' => true]),
                'amenities' => json_encode(['pallet_jack', 'shelving']),
                'start_date' => Carbon::now()->subDays(15),
                'end_date' => Carbon::now()->addMonths(3),
                'duration_months' => 3,
                'access_hours' => 'Business hours',
                'special_instructions' => 'Stack carefully, do not exceed 3 pallets high',
                'monthly_rate' => 5000.00,
                'security_deposit' => 10000.00,
                'setup_fee' => 500.00,
                'total_amount' => 15000.00,
                'tax_amount' => 1500.00,
                'final_amount' => 17000.00,
                'payment_method' => 'credit_card',
                'payment_status' => 'paid',
                'payment_date' => Carbon::now()->subDays(20),
                'transaction_reference' => 'TXN-' . strtoupper(substr(uniqid(), -10)),
                'terms_accepted' => true,
                'insurance_required' => true,
                'notes' => 'Long-term client, priority handling',
            ],
            [
                'user_id' => 22,
                'warehouse_unit_id' => 1,
                'booking_reference' => 'WH-' . strtoupper(substr(uniqid(), -8)),
                'status' => 'active',
                'company_name' => 'Global Imports Ltd',
                'contact_person' => 'Robert Brown',
                'phone' => '+1-555-1003',
                'email' => 'r.brown@globalimports.com',
                'company_address' => '789 Import Road, Seattle, WA 98101',
                'storage_type' => 'dry',
                'required_space' => 2000.00,
                'goods_type' => 'Textiles',
                'goods_description' => 'Imported fabrics and clothing',
                'estimated_weight' => 10000.00,
                'special_requirements' => json_encode(['humidity_control' => true]),
                'amenities' => json_encode(['loading_dock', 'cart']),
                'start_date' => Carbon::now()->subMonths(1),
                'end_date' => Carbon::now()->addMonths(11),
                'duration_months' => 12,
                'access_hours' => 'Mon-Fri 8AM-6PM',
                'special_instructions' => 'Keep away from moisture',
                'monthly_rate' => 5000.00,
                'security_deposit' => 10000.00,
                'setup_fee' => 500.00,
                'total_amount' => 60000.00,
                'tax_amount' => 6000.00,
                'final_amount' => 66500.00,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'paid',
                'payment_date' => Carbon::now()->subMonths(1)->subDays(5),
                'transaction_reference' => 'TXN-' . strtoupper(substr(uniqid(), -10)),
                'terms_accepted' => true,
                'insurance_required' => true,
                'notes' => 'Regular monthly storage',
            ],
            [
                'user_id' => 22,
                'warehouse_unit_id' => 1,
                'booking_reference' => 'WH-' . strtoupper(substr(uniqid(), -8)),
                'status' => 'completed',
                'company_name' => 'Seasonal Storage Co',
                'contact_person' => 'Mary Johnson',
                'phone' => '+1-555-1004',
                'email' => 'mary.j@seasonal.com',
                'company_address' => '321 Storage Lane, Boston, MA 02101',
                'storage_type' => 'dry',
                'required_space' => 800.00,
                'goods_type' => 'Retail Products',
                'goods_description' => 'Seasonal merchandise and displays',
                'estimated_weight' => 3000.00,
                'special_requirements' => json_encode(['easy_access' => true]),
                'amenities' => json_encode(['forklift']),
                'start_date' => Carbon::now()->subMonths(4),
                'end_date' => Carbon::now()->subMonths(1),
                'duration_months' => 3,
                'access_hours' => '24/7',
                'special_instructions' => 'Quick turnaround needed',
                'monthly_rate' => 5000.00,
                'security_deposit' => 10000.00,
                'setup_fee' => 500.00,
                'total_amount' => 15000.00,
                'tax_amount' => 1500.00,
                'final_amount' => 17000.00,
                'payment_method' => 'credit_card',
                'payment_status' => 'paid',
                'payment_date' => Carbon::now()->subMonths(4)->subDays(3),
                'transaction_reference' => 'TXN-' . strtoupper(substr(uniqid(), -10)),
                'terms_accepted' => true,
                'insurance_required' => false,
                'notes' => 'Booking completed successfully',
            ],
            [
                'user_id' => 22,
                'warehouse_unit_id' => 1,
                'booking_reference' => 'WH-' . strtoupper(substr(uniqid(), -8)),
                'status' => 'cancelled',
                'company_name' => 'QuickShip Logistics',
                'contact_person' => 'David Wilson',
                'phone' => '+1-555-1005',
                'email' => 'd.wilson@quickship.com',
                'company_address' => '654 Logistics Blvd, Chicago, IL 60601',
                'storage_type' => 'dry',
                'required_space' => 1200.00,
                'goods_type' => 'Automotive Parts',
                'goods_description' => 'Car parts and accessories',
                'estimated_weight' => 6000.00,
                'special_requirements' => json_encode(['organized_storage' => true]),
                'amenities' => json_encode(['shelving', 'pallet_jack']),
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addMonths(6),
                'duration_months' => 6,
                'access_hours' => 'Business hours',
                'special_instructions' => 'Organize by part number',
                'monthly_rate' => 5000.00,
                'security_deposit' => 10000.00,
                'setup_fee' => 500.00,
                'total_amount' => 30000.00,
                'tax_amount' => 3000.00,
                'final_amount' => 33500.00,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'pending',
                'terms_accepted' => true,
                'insurance_required' => true,
                'notes' => 'Cancelled due to change in business plans',
            ],
        ];

        foreach ($bookings as $bookingData) {
            WarehouseBooking::create($bookingData);
        }

        $this->command->info('Warehouse booking test data seeded successfully!');
        $this->command->info('Created ' . count($bookings) . ' bookings for warehouse_unit_id = 1 and user_id = 22');
    }
}
