import { BadgeDollarSign, BellRing, Clock3, KeyRound, MapPinned, Printer, ShieldCheck, Users } from "lucide-react";

// Extracted from Settings.jsx to reduce file size and Babel deopt warnings.
export const NOTIFICATION_EVENT_MATRIX_DEFAULT = {
    shipment_placed: { client: { email: true, inApp: false }, internal: { email: false, inApp: false } },
    booking_confirmed: { client: { email: true, inApp: false }, internal: { email: false, inApp: false } },
    booking_cancelled: { client: { email: true, inApp: true }, internal: { email: true, inApp: true } },
    tracking_picked_up: { client: { email: true, inApp: true }, internal: { email: false, inApp: false } },
    tracking_out_for_delivery: { client: { email: true, inApp: true }, internal: { email: false, inApp: false } },
    tracking_delivered: { client: { email: true, inApp: true }, internal: { email: false, inApp: false } },
    payment_paid: { client: { email: true, inApp: true }, internal: { email: false, inApp: false } },
    payment_failed: { client: { email: true, inApp: true }, internal: { email: true, inApp: true } },
    payment_cancelled: { client: { email: true, inApp: true }, internal: { email: true, inApp: true } },
    internal_exception: { internal: { email: true, inApp: true } },
    internal_sla_risk: { internal: { email: true, inApp: true } },
};

export const LEGACY_NOTIFICATION_MAP = {
    notifyClientShipmentPlaced: { event: "shipment_placed", audience: "client" },
    notifyClientBookingConfirmed: { event: "booking_confirmed", audience: "client" },
    notifyClientBookingCancelled: { event: "booking_cancelled", audience: "client" },
    notifyClientPickup: { event: "tracking_picked_up", audience: "client" },
    notifyClientOutForDelivery: { event: "tracking_out_for_delivery", audience: "client" },
    notifyClientDelivered: { event: "tracking_delivered", audience: "client" },
    notifyClientPaymentPaid: { event: "payment_paid", audience: "client" },
    notifyClientPaymentFailed: { event: "payment_failed", audience: "client" },
    notifyClientPaymentCancelled: { event: "payment_cancelled", audience: "client" },
    notifyInternalException: { event: "internal_exception", audience: "internal" },
    notifyInternalSlaRisk: { event: "internal_sla_risk", audience: "internal" },
};

export const NOTIFICATION_EVENT_LABELS = {
    shipment_placed: "Shipment Placed",
    booking_confirmed: "Booking Confirmed",
    booking_cancelled: "Booking Cancelled",
    tracking_picked_up: "Tracking Picked Up",
    tracking_out_for_delivery: "Out For Delivery",
    tracking_delivered: "Delivered",
    payment_paid: "Payment Paid",
    payment_failed: "Payment Failed",
    payment_cancelled: "Payment Cancelled",
    internal_exception: "Internal Exception",
    internal_sla_risk: "Internal SLA Risk",
};

export const buildLegacyNotificationFlags = (eventMatrix) => {
    const matrix = eventMatrix && typeof eventMatrix === "object" ? eventMatrix : {};
    return Object.entries(LEGACY_NOTIFICATION_MAP).reduce((acc, [legacyKey, mapping]) => {
        const fallback = Boolean(NOTIFICATION_EVENT_MATRIX_DEFAULT?.[mapping.event]?.[mapping.audience]?.email);
        const rawValue = matrix?.[mapping.event]?.[mapping.audience]?.email;
        acc[legacyKey] = typeof rawValue === "boolean" ? rawValue : fallback;
        return acc;
    }, {});
};

export const buildDefaultNotificationSettings = () => {
    const eventMatrix = JSON.parse(JSON.stringify(NOTIFICATION_EVENT_MATRIX_DEFAULT));
    return {
        ...buildLegacyNotificationFlags(eventMatrix),
        version: 2,
        channels: {
            email: { enabled: true },
            inApp: { enabled: true },
        },
        clientRecipients: {
            requester: true,
            sender: true,
            recipient: true,
            extraEmails: [],
        },
        internalRecipients: {
            roleNames: ["ops_lead"],
            userIds: [],
            extraEmails: [],
        },
        eventMatrix,
        delivery: {
            quietHours: {
                enabled: false,
                start: "22:00",
                end: "06:00",
                timezone: "Asia/Colombo",
            },
            digest: {
                enabled: false,
                frequency: "daily",
                time: "09:00",
                timezone: "Asia/Colombo",
            },
        },
        deliverability: {
            fromName: "Transport Jaan Courier",
            fromEmail: "",
            replyTo: "",
            respectSuppression: true,
        },
    };
};

export const DEFAULT_NOTIFICATION_SETTINGS = buildDefaultNotificationSettings();

export const DEFAULT_SETTINGS = {
    business: {
        companyName: "Sonnac Lanka Enterprises",
        supportEmail: "ops@sonnac.lk",
        hotline: "+94 11 123 4567",
        primaryHub: "Colombo Hub",
        serviceZones: "Colombo, Gampaha, Kalutara, Kandy",
    },
    operations: {
        autoAcceptBookings: false,
        workStart: "08:00",
        workEnd: "20:00",
        sameDayCutoff: "14:00",
        maxDailyBookings: 350,
    },
    sla: {
        expressHours: 8,
        economyHours: 24,
        breachAlertMinutes: 90,
        autoEscalateExceptions: true,
    },
    tracking: {
        noScan6h: true,
        noScan12h: true,
        noScan24h: false,
        requirePodPhoto: true,
        requirePodSignature: false,
        allowManualScanCorrection: true,
    },
    notifications: {
        ...DEFAULT_NOTIFICATION_SETTINGS,
    },
    integrations: {
        webhookUrl: "",
        apiKeyAlias: "CourierProdKey",
        retryWindowMinutes: 15,
        rotateKeysEveryDays: 90,
    },
    services: {
        cod: {
            acceptCodAtCheckout: false,
            allowCodForDomestic: true,
            allowCodForInternational: false,
            allowTeamOverride: false,
        },
    },
    labels: {
        defaults: {
            domestic: {
                templateId: null,
                sizeId: null,
            },
            international: {
                templateId: null,
                sizeId: null,
            },
        },
        printPolicy: {
            bulkAsyncThreshold: 50,
            bulkHardLimit: 200,
            allowCustomSizes: true,
            allowTemplateUpload: true,
            allowHtmlTemplates: true,
            allowPdfBackground: true,
        },
    },
    pricing: {
        localization: {
            domestic: {
                baseCurrency: "LKR",
                displayCurrency: "LKR",
                locale: "en-LK",
                exchangeRateProvider: "frankfurter.app",
                autoLiveRates: true,
                manualRates: {
                    LKR: 1,
                    USD: 0.00308,
                    EUR: 0.00284,
                },
                lastSyncedAt: null,
            },
            international: {
                baseCurrency: "LKR",
                displayCurrency: "LKR",
                locale: "en-LK",
                exchangeRateProvider: "frankfurter.app",
                autoLiveRates: true,
                manualRates: {
                    LKR: 1,
                    USD: 0.00308,
                    EUR: 0.00284,
                },
                lastSyncedAt: null,
            },
        },
        formula: {
            domestic: {
                volumetricDivisor: 5000,
                useChargeableWeight: true,
                fuelSurchargePercent: 0,
                handlingFee: 0,
                taxPercent: 0,
                roundTo: 2,
            },
            international: {
                volumetricDivisor: 5000,
                useChargeableWeight: true,
                fuelSurchargePercent: 0,
                handlingFee: 0,
                taxPercent: 0,
                roundTo: 2,
            },
        },
        serviceCatalog: {
            domestic: [
                { key: "same_day", label: "Same Day", promisedSlaDays: 1, cutoffTime: "10:30", isActive: true, sortOrder: 1 },
                { key: "next_day", label: "Next Day", promisedSlaDays: 1, cutoffTime: "15:00", isActive: true, sortOrder: 2 },
                { key: "two_three_day", label: "2-3 Day", promisedSlaDays: 3, cutoffTime: "17:00", isActive: true, sortOrder: 3 },
                { key: "economy", label: "Economy", promisedSlaDays: 5, cutoffTime: "18:00", isActive: true, sortOrder: 4 },
            ],
            international: [
                { key: "next_day", label: "Next Day", promisedSlaDays: 2, cutoffTime: "13:00", isActive: true, sortOrder: 1 },
                { key: "two_three_day", label: "2-3 Day", promisedSlaDays: 3, cutoffTime: "16:00", isActive: true, sortOrder: 2 },
                { key: "economy", label: "Economy", promisedSlaDays: 6, cutoffTime: "18:00", isActive: true, sortOrder: 3 },
            ],
        },
        zoneMaster: {
            domestic: [],
            international: [],
        },
        laneMatrix: {
            enabled: {
                domestic: false,
                international: false,
            },
            domestic: [],
            international: [],
        },
        policyModules: {
            domestic: {
                remoteAreaSurcharge: {
                    enabled: false,
                    flatFee: 0,
                    applyOnOrigin: false,
                    applyOnDestination: true,
                    postalCodePrefixes: [],
                    cityKeywords: [],
                },
                oversizeOverweightRules: {
                    enabled: false,
                    maxWeightKg: 25,
                    overweightPerKgFee: 0,
                    maxLengthCm: 120,
                    maxWidthCm: 80,
                    maxHeightCm: 80,
                    oversizeFlatFee: 0,
                },
                peakHolidaySurcharge: {
                    enabled: false,
                    peakStartTime: "17:00",
                    peakEndTime: "21:00",
                    daysOfWeek: [1, 2, 3, 4, 5],
                    peakPercent: 0,
                    peakFlatFee: 0,
                    holidayDates: [],
                    holidayPercent: 0,
                    holidayFlatFee: 0,
                },
                codFee: {
                    enabled: false,
                    flatFee: 0,
                    percentOfDeclaredValue: 0,
                    minFee: 0,
                    maxFee: null,
                },
                minimumShipmentCharge: {
                    enabled: true,
                    minimumTotal: 0,
                },
                customerContractPricing: {
                    enabled: false,
                    contracts: [],
                },
                quoteRuntimeGovernance: {
                    enabled: false,
                    fieldLocks: {
                        enabled: false,
                        lockShipmentServiceLevel: true,
                        lockPackageServiceLevel: true,
                        lockPackageCourierProvider: true,
                        lockQuoteTotal: true,
                    },
                    discountGuardrails: {
                        enabled: false,
                        maxDiscountPercent: 0,
                        maxDiscountAmountUsd: 0,
                    },
                    floorPriceGuardrail: {
                        enabled: false,
                        minimumTotalUsd: 0,
                    },
                },
                speedEtaTierEngine: {
                    enabled: false,
                    enforceFixedNamedTiers: true,
                    enforceTierPricingMultiplier: true,
                    tiers: {
                        priority_4h: {
                            enabled: true,
                            etaLabel: "Priority 4 Hours",
                            etaMinDays: 0,
                            etaMaxDays: 0,
                            priceMultiplier: 1.45,
                            maxDistanceKm: 35,
                            maxWeightKg: 12,
                            minLeadHours: 0.5,
                            maxLeadHours: 4,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        same_day: {
                            enabled: true,
                            etaLabel: "Same Day",
                            etaMinDays: 0,
                            etaMaxDays: 1,
                            priceMultiplier: 1.25,
                            maxDistanceKm: 80,
                            maxWeightKg: 20,
                            minLeadHours: 1,
                            maxLeadHours: 12,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        next_day: {
                            enabled: true,
                            etaLabel: "Next Day",
                            etaMinDays: 1,
                            etaMaxDays: 2,
                            priceMultiplier: 1.12,
                            maxDistanceKm: 250,
                            maxWeightKg: 30,
                            minLeadHours: 2,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        two_three_day: {
                            enabled: true,
                            etaLabel: "2-3 Days",
                            etaMinDays: 2,
                            etaMaxDays: 3,
                            priceMultiplier: 1,
                            maxDistanceKm: null,
                            maxWeightKg: null,
                            minLeadHours: 0,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        economy: {
                            enabled: true,
                            etaLabel: "Economy",
                            etaMinDays: 4,
                            etaMaxDays: 7,
                            priceMultiplier: 0.92,
                            maxDistanceKm: null,
                            maxWeightKg: null,
                            minLeadHours: 0,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                    },
                },
                internationalDimensionsEngine: {
                    enabled: false,
                    enforceForInternationalOnly: true,
                    unitTypeMultipliers: {
                        parcel: 1.0,
                        pallet: 1.18,
                        crate: 1.24,
                        container_20ft: 1.55,
                        container_40ft: 1.85,
                    },
                    routeClassMultipliers: {
                        standard: 1.0,
                        express_corridor: 1.12,
                        remote_corridor: 1.22,
                        multimodal: 1.3,
                    },
                    handlingClassMultipliers: {
                        standard: 1.0,
                        fragile: 1.08,
                        hazardous: 1.2,
                        cold_chain: 1.18,
                        heavy_lift: 1.26,
                    },
                    w2wOption: {
                        enabled: true,
                        strictForInternational: true,
                        defaultMode: "door_to_door",
                        minimumUnitCount: 1,
                        maximumUnitCount: null,
                        modeMultipliers: {
                            door_to_door: 1.15,
                            port_to_port: 0.92,
                            hybrid: 1,
                        },
                    },
                },
            },
            international: {
                remoteAreaSurcharge: {
                    enabled: false,
                    flatFee: 0,
                    applyOnOrigin: false,
                    applyOnDestination: true,
                    postalCodePrefixes: [],
                    cityKeywords: [],
                },
                oversizeOverweightRules: {
                    enabled: false,
                    maxWeightKg: 25,
                    overweightPerKgFee: 0,
                    maxLengthCm: 120,
                    maxWidthCm: 80,
                    maxHeightCm: 80,
                    oversizeFlatFee: 0,
                },
                peakHolidaySurcharge: {
                    enabled: false,
                    peakStartTime: "17:00",
                    peakEndTime: "21:00",
                    daysOfWeek: [1, 2, 3, 4, 5],
                    peakPercent: 0,
                    peakFlatFee: 0,
                    holidayDates: [],
                    holidayPercent: 0,
                    holidayFlatFee: 0,
                },
                codFee: {
                    enabled: false,
                    flatFee: 0,
                    percentOfDeclaredValue: 0,
                    minFee: 0,
                    maxFee: null,
                },
                minimumShipmentCharge: {
                    enabled: true,
                    minimumTotal: 0,
                },
                customerContractPricing: {
                    enabled: false,
                    contracts: [],
                },
                quoteRuntimeGovernance: {
                    enabled: false,
                    fieldLocks: {
                        enabled: false,
                        lockShipmentServiceLevel: true,
                        lockPackageServiceLevel: true,
                        lockPackageCourierProvider: true,
                        lockQuoteTotal: true,
                    },
                    discountGuardrails: {
                        enabled: false,
                        maxDiscountPercent: 0,
                        maxDiscountAmountUsd: 0,
                    },
                    floorPriceGuardrail: {
                        enabled: false,
                        minimumTotalUsd: 0,
                    },
                },
                speedEtaTierEngine: {
                    enabled: false,
                    enforceFixedNamedTiers: true,
                    enforceTierPricingMultiplier: true,
                    tiers: {
                        priority_4h: {
                            enabled: true,
                            etaLabel: "Priority 4 Hours",
                            etaMinDays: 0,
                            etaMaxDays: 0,
                            priceMultiplier: 1.45,
                            maxDistanceKm: 35,
                            maxWeightKg: 12,
                            minLeadHours: 0.5,
                            maxLeadHours: 4,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        same_day: {
                            enabled: true,
                            etaLabel: "Same Day",
                            etaMinDays: 0,
                            etaMaxDays: 1,
                            priceMultiplier: 1.25,
                            maxDistanceKm: 80,
                            maxWeightKg: 20,
                            minLeadHours: 1,
                            maxLeadHours: 12,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        next_day: {
                            enabled: true,
                            etaLabel: "Next Day",
                            etaMinDays: 1,
                            etaMaxDays: 2,
                            priceMultiplier: 1.12,
                            maxDistanceKm: 250,
                            maxWeightKg: 30,
                            minLeadHours: 2,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        two_three_day: {
                            enabled: true,
                            etaLabel: "2-3 Days",
                            etaMinDays: 2,
                            etaMaxDays: 3,
                            priceMultiplier: 1,
                            maxDistanceKm: null,
                            maxWeightKg: null,
                            minLeadHours: 0,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                        economy: {
                            enabled: true,
                            etaLabel: "Economy",
                            etaMinDays: 4,
                            etaMaxDays: 7,
                            priceMultiplier: 0.92,
                            maxDistanceKm: null,
                            maxWeightKg: null,
                            minLeadHours: 0,
                            maxLeadHours: null,
                            allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
                            blackoutDates: [],
                        },
                    },
                },
                internationalDimensionsEngine: {
                    enabled: false,
                    enforceForInternationalOnly: true,
                    unitTypeMultipliers: {
                        parcel: 1.0,
                        pallet: 1.18,
                        crate: 1.24,
                        container_20ft: 1.55,
                        container_40ft: 1.85,
                    },
                    routeClassMultipliers: {
                        standard: 1.0,
                        express_corridor: 1.12,
                        remote_corridor: 1.22,
                        multimodal: 1.3,
                    },
                    handlingClassMultipliers: {
                        standard: 1.0,
                        fragile: 1.08,
                        hazardous: 1.2,
                        cold_chain: 1.18,
                        heavy_lift: 1.26,
                    },
                    w2wOption: {
                        enabled: true,
                        strictForInternational: true,
                        defaultMode: "door_to_door",
                        minimumUnitCount: 1,
                        maximumUnitCount: null,
                        modeMultipliers: {
                            door_to_door: 1.15,
                            port_to_port: 0.92,
                            hybrid: 1,
                        },
                    },
                },
            },
        },
        categories: {
            domestic: [
                {
                    id: "domestic_within_3_days",
                    label: "Within 3 Days",
                    serviceLevelKey: "two_three_day",
                    slaDays: 3,
                    basePrice: 250,
                    perKgPrice: 35,
                    minPrice: 250,
                    priorityMultiplier: 1,
                },
                {
                    id: "domestic_one_day",
                    label: "One Day",
                    serviceLevelKey: "next_day",
                    slaDays: 1,
                    basePrice: 1000,
                    perKgPrice: 70,
                    minPrice: 1000,
                    priorityMultiplier: 1,
                },
            ],
            international: [
                {
                    id: "international_standard",
                    label: "international Standard",
                    serviceLevelKey: "two_three_day",
                    slaDays: 4,
                    basePrice: 1400,
                    perKgPrice: 90,
                    minPrice: 1400,
                    priorityMultiplier: 1,
                },
                {
                    id: "international_express",
                    label: "international Express",
                    serviceLevelKey: "next_day",
                    slaDays: 2,
                    basePrice: 2200,
                    perKgPrice: 130,
                    minPrice: 2200,
                    priorityMultiplier: 1.12,
                },
            ],
        },
        governance: {
            domestic: {
                requireApproval: false,
                approverRoles: ["courier_owner", "courier_admin"],
                draftVersion: 1,
                publishedVersion: 1,
                publishedAt: null,
                publishedBy: null,
                pendingApproval: null,
                scheduledPublish: null,
                versionHistory: [],
                changeLog: [],
            },
            international: {
                requireApproval: false,
                approverRoles: ["courier_owner", "courier_admin"],
                draftVersion: 1,
                publishedVersion: 1,
                publishedAt: null,
                publishedBy: null,
                pendingApproval: null,
                scheduledPublish: null,
                versionHistory: [],
                changeLog: [],
            },
        },
    },
    team: {
        dispatcherCanCancel: false,
        opsLeadCanReassign: true,
        financeCanViewRates: true,
        enforce2FA: true,
        approvalControl: {
            enabled: true,
            makerChecker: true,
            approvalTtlMinutes: 240,
            sensitiveActions: {
                high_value_cancellation: {
                    enabled: true,
                    minAmount: 50000,
                    requiredApprovals: 1,
                },
                refund: {
                    enabled: true,
                    level1MinAmount: 25000,
                    level2MinAmount: 100000,
                    requiredApprovalsLevel1: 1,
                    requiredApprovalsLevel2: 2,
                },
                cod_override: {
                    enabled: true,
                    level1MinAmount: 25000,
                    level2MinAmount: 100000,
                    requiredApprovalsLevel1: 1,
                    requiredApprovalsLevel2: 2,
                },
                ownership_transfer: {
                    enabled: true,
                    requiredApprovals: 2,
                },
                client_list_export: {
                    enabled: true,
                    minRows: 100,
                    requiredApprovals: 1,
                },
            },
        },
        sodControl: {
            enabled: true,
            toxicCombinations: [
                {
                    key: "refund_create_and_approve",
                    label: "Cannot both create refunds and approve refunds",
                    permissions: ["courier.refunds.create", "courier.refunds.approve"],
                    enforceRoleEdit: true,
                    enforceUserAssignment: true,
                    enabled: true,
                },
                {
                    key: "assign_permissions_and_approve_access_request",
                    label: "Cannot both assign permissions and approve access requests",
                    permissions: ["courier.team.assign_permissions", "courier.team.access_requests.approve"],
                    enforceRoleEdit: true,
                    enforceUserAssignment: true,
                    enabled: true,
                },
            ],
        },
        temporaryAccessControl: {
            enabled: true,
            defaultDurationMinutes: 120,
            maxDurationMinutes: 240,
            requireTicket: true,
            requireReason: true,
            makerChecker: true,
            allowedElevationRoles: ["courier_admin"],
            breakGlass: {
                enabled: true,
                defaultDurationMinutes: 30,
                maxDurationMinutes: 60,
                requireTicket: true,
                requireReason: true,
                notifyOwners: true,
                notifyRequester: true,
                notifyTarget: true,
                alertEmails: [],
                alertWebhookUrl: "",
            },
        },
        accessReviewControl: {
            enabled: true,
            reviewFrequency: "monthly",
            reviewDueDays: 7,
            requireManagerCertification: true,
            autoDisableStaleAccounts: true,
            staleAccountDays: 45,
            alertDormantPrivilegedUsers: true,
            dormantPrivilegedDays: 21,
            privilegedRoles: ["courier_owner", "courier_admin", "courier_finance"],
        },
        apiServiceAccessControl: {
            enabled: true,
            requireExpiry: true,
            defaultTtlDays: 30,
            maxTtlDays: 90,
            allowWebhookScopes: true,
            maxActiveKeysPerServiceAccount: 2,
            webhookScopesCatalog: ["webhook.events.write"],
        },
        sessionSecurity: {
            enabled: true,
            deviceTrust: {
                enabled: true,
                enforceForRoles: ["courier_owner", "courier_admin"],
                enforceForUserIds: [],
                trustDurationDays: 30,
            },
            concurrentSessions: {
                enabled: true,
                mode: "revoke_oldest",
                defaultLimit: 3,
                limitsByRole: {
                    courier_owner: 2,
                    courier_admin: 2,
                    courier_dispatcher: 3,
                    courier_finance: 2,
                    courier_support: 3,
                    courier_tracking_officer: 4,
                    courier_viewer: 5,
                },
            },
            anomalyDetection: {
                enabled: true,
                rapidSwitchMinutes: 120,
                clearStepUpOnAnomaly: false,
                ipAllowList: [],
                ipDenyList: [],
            },
            stepUp: {
                enabled: true,
                ttlMinutes: 120,
                twoFactorTtlMinutes: 120,
                sensitiveRouteNames: [
                    "courierService.team.access.update",
                    "courierService.team.bulk",
                    "courierService.team.transfer-ownership",
                    "courierService.team.roles.store",
                    "courierService.team.roles.store-template",
                    "courierService.team.roles.clone",
                    "courierService.team.roles.update",
                    "courierService.team.sensitive-approvals.approve",
                    "courierService.team.sensitive-approvals.reject",
                    "courierService.team.temporary-access.approve",
                    "courierService.team.temporary-access.reject",
                    "courierService.team.temporary-access.revoke",
                    "courierService.team.temporary-access.break-glass",
                    "courierService.team.access-reviews.certify",
                    "courierService.team.api-access.store",
                    "courierService.team.api-access.rotate",
                    "courierService.team.api-access.revoke",
                ],
            },
            mandatory2FA: {
                enabled: true,
                roles: ["courier_owner", "courier_admin"],
                userIds: [],
                forSensitiveActions: true,
            },
        },
        teamAccessControl: {
            defaultDirectPermissionsByRole: {},
            defaultDataScopeByRole: {},
            onboardingBundles: [],
        },
        permissionModel: {
            enabled: true,
            rolePolicies: {},
            fieldVisibility: {
                rate_cards: { visibleToRoles: [] },
                margin: { visibleToRoles: [] },
                customer_phone: { visibleToRoles: [] },
                payment_refs: { visibleToRoles: [] },
            },
        },
    },
};

export const TAB_CONFIG = [
    { key: "business", label: "Business", icon: MapPinned },
    { key: "operations", label: "Operations", icon: Clock3 },
    { key: "sla", label: "SLA", icon: ShieldCheck },
    { key: "tracking", label: "Tracking", icon: MapPinned },
    { key: "notifications", label: "Notifications", icon: BellRing },
    { key: "integrations", label: "Integrations", icon: KeyRound },
    { key: "services", label: "Services", icon: ShieldCheck },
    { key: "labels", label: "Labels", icon: Printer },
    { key: "pricing", label: "Pricing", icon: BadgeDollarSign },
    { key: "team", label: "Team Access", icon: Users },
];

export const CURRENCY_OPTIONS = [
    "LKR",
    "USD",
    "EUR",
    "GBP",
    "AED",
    "AUD",
    "CAD",
    "CHF",
    "CNY",
    "HKD",
    "INR",
    "JPY",
    "SGD",
];

export const LABEL_UNIT_OPTIONS = [
    { value: "mm", label: "mm" },
    { value: "cm", label: "cm" },
    { value: "in", label: "in" },
];

export const TEAM_ACCESS_TOPIC_CONFIG = [
    { key: "policy-controls", label: "Team Policy Controls" },
    { key: "user-defaults", label: "Team User Creation Defaults" },
    { key: "api-access", label: "API and Service Access" },
    { key: "role-studio", label: "Role Studio" },
];

export const PRICING_TOPIC_CONFIG = [
    { key: "currency-formula", label: "Currency and Formula", sectionId: "pricing-topic-currency-formula" },
    { key: "policy-modules", label: "Policy Modules", sectionId: "pricing-topic-policy-modules" },
    { key: "contracts", label: "Customer Contracts", sectionId: "pricing-topic-contracts" },
    { key: "service-catalog", label: "Service Catalog", sectionId: "pricing-topic-service-catalog" },
    { key: "governance", label: "Pricing Governance", sectionId: "pricing-topic-governance" },
    { key: "rate-cards", label: "Rate Cards", sectionId: "pricing-topic-rate-cards" },
    { key: "zone-master", label: "Zone Master", sectionId: "pricing-topic-zone-master" },
    { key: "lane-matrix", label: "Lane Matrix", sectionId: "pricing-topic-lane-matrix" },
    { key: "preview", label: "Formula Preview", sectionId: "pricing-topic-preview" },
];

export const COD_CAPABILITY_CATEGORY_LABEL = "Domestic";

export const DEFAULT_SPEED_ETA_TIER_TEMPLATE = {
    enabled: true,
    etaLabel: "Custom Tier",
    etaMinDays: 0,
    etaMaxDays: null,
    priceMultiplier: 1,
    maxDistanceKm: null,
    maxWeightKg: null,
    minLeadHours: 0,
    maxLeadHours: null,
    allowedPickupDays: [1, 2, 3, 4, 5, 6, 7],
    blackoutDates: [],
};


export const DEFAULT_ROLE_SCOPE_CONSTRAINTS = {
    regionZones: [],
    hubBranches: [],
    allowedCustomerIds: [],
    keyAccountsOnly: false,
    enforceShiftWindow: false,
    shiftStart: "00:00",
    shiftEnd: "23:59",
    allowedEnvironments: ["production", "sandbox"],
    blockedActionsByEnvironment: {
        production: [],
        sandbox: [],
    },
    policyRules: [],
};
